apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: airflow
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://airflow.apache.org'
    targetRevision: v1.7.0
    chart: airflow
    helm:
      parameters:
        - name: "images.airflow.repository"
          value: '111355452311.dkr.ecr.us-east-1.amazonaws.com/mysite'
        - name: "images.airflow.tag"
          value: '3bcc0a1a'
        - name: "fernetKey"
          value: 'zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI='
        - name: "executor"
          value: 'KubernetesExecutor'
        - name: "createUserJob.useHelmHooks"
          value: 'false'
        - name: "migrateDatabaseJob.useHelmHooks"
          value: 'false'
        - name: "extraEnv"
          value: |
            - name: "AIRFLOW__CORE__LOAD_EXAMPLES" 
              value: 'False'
            - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE" 
              value: 'False'
            - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
              value: 'airflow'
            - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
              value: '111355452311.dkr.ecr.us-east-1.amazonaws.com/mysite'
            - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
              value: '3bcc0a1a'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
